language: csharp
solution: solution-name.sln
mono: none
dotnet: 2.2.401
install:
 - nuget restore solution-name.sln
 - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
 - dotnet restore
 - msbuild /p:Configuration=Release solution-name.sln
 - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll